---
title: "Production Investment and Economic Dispatch in Sustainble Energy System"
output: html_notebook
author: Edward J. Xu (<edxu96@outlook.com>)
date: "`r Sys.Date()`"
---

```{r}
rm(list = ls())
setwd("~/GitHub/Optivest.jl/Power-System/PIED")
```

```{r}
library(tidyverse)
library(magrittr)
library(ggplot2)
library(tidyr)
library(kableExtra)
library(knitr)
```

```{r, message=FALSE}
knitr::opts_chunk$set(
  collapse = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.align = "center",
  fig.asp = 9/16,
  fig.width = 5,
  warning = FALSE,
  message = FALSE
)
```

```{r, message=FALSE}
ti_dk1 <- 
  read_csv2("./data/Electricity-Dispatch_DK1.csv") %>%
  mutate(OffshoreWindPower = as.numeric(OffshoreWindPower)) %>%
  mutate(TotalLoad = TotalLoad / 100) %>%
  mutate(OnshoreWindPower = OnshoreWindPower / 100)
```

```{r}
get_result_dispatch <- function(str_file, z){
  ti <-
    read_csv(str_file, col_names = c("gt", "bio")) %>%
    mutate(index = row_number()) %>%
    bind_cols(ti_dk1[1:168, 4]) %>%
    bind_cols(ti_dk1[1:168, 5:6]) %>%
    mutate(wind_total = (OnshoreWindPower + OffshoreWindPower) * z) %>%
    mutate(demand = TotalLoad) %>%
    mutate(wind_net = demand - gt - bio) %>%
    select(index, demand, wind_total, wind_net, gt, bio)

  return(ti)
}

plot_dispatch <- function(ti, y_gt, y_bio){
  ti %>%
    gather(-index, key = "whi", value = "power") %>%
    ggplot() + 
      geom_line(mapping = aes(x = index, y = power, color = whi)) +
      geom_hline(yintercept = y_gt, color = "grey", linetype = "dashed") +
      geom_text(aes(0, y_gt, label = y_gt), size = 3) + 
      geom_hline(
        yintercept = y_gt * 0.23, color = "grey", linetype = "dashed"
        ) +
      geom_text(aes(0, y_gt * 0.23, label = y_gt * 0.23), size = 3) + 
      geom_hline(yintercept = y_bio, color = "grey", linetype = "dashed") +
      geom_text(aes(0, y_bio, label = y_bio), size = 3) + 
      geom_hline(
        yintercept = y_bio * 0.5, color = "grey", linetype = "dashed"
        ) +
      geom_text(aes(0,  y_bio * 0.5, label =  y_bio * 0.5), size = 3) + 
      labs(
        title = "Demand, Wind Power Output, Dispatch of GT and Bio",
        x = "Time Index", y = "Power (MW)"
        )
}

plot_dispatch_stack <- function(ti){
  ti %>%
    select(index, bio, gt, wind_net) %>%
    gather(-index, key = "whi", value = "power") %>%
    ggplot() +
      geom_area(mapping = aes(x = index, y = power, fill = whi)) +
      labs(
        title = "Stacked Area Plot of Wind, GT Dispatch, Bio Dispatch",
        x = "Time Index", y = "Power (MW)"
        )
}

#' Get the result
get_result_dispatch_ev <- function(str_file_wind_u, str_file_result, z){
  ti_wind_u <-
  read_csv(str_file_wind_u, col_names = c("wind", "u")) %>%
  mutate(wind_net = -wind) %>%
  select(u)
  # select(wind_net, u)

  ti <-
    read_csv(str_file_result, col_names = c("gt", "bio")) %>%
    mutate(index = row_number()) %>%
    bind_cols(ti_dk1[1:168, 4]) %>%
    bind_cols(ti_dk1[1:168, 5:6]) %>%
    mutate(wind_total = (OnshoreWindPower + OffshoreWindPower) * z) %>%
    mutate(demand = TotalLoad) %>%
    bind_cols(ti_wind_u) %>%
    select(index, demand, wind_total, u, gt, bio)
  
  return(ti)
}


plot_dispatch_ev <- function(ti, y_gt, y_bio){
  ti %>% 
    mutate(wind_net = demand + u - gt - bio) %>%
    mutate(u = -u) %>%
    mutate(demand = -demand) %>%
    gather(-index, key = "whi", value = "power") %>%
    ggplot() + 
      geom_line(mapping = aes(x = index, y = power, color = whi)) +
      geom_hline(yintercept = y_gt, color = "grey", linetype = "dashed") +
      geom_text(aes(0, y_gt, label = y_gt), size = 3) + 
      geom_hline(
        yintercept = y_gt * 0.23, color = "grey", linetype = "dashed"
        ) +
      geom_text(aes(0, y_gt * 0.23, label = y_gt * 0.23), size = 3) + 
      geom_hline(yintercept = y_bio, color = "grey", linetype = "dashed") +
      geom_text(aes(0, y_bio, label = y_bio), size = 3) + 
      geom_hline(
        yintercept = y_bio * 0.5, color = "grey", linetype = "dashed"
        ) +
      geom_text(aes(0,  y_bio * 0.5, label =  y_bio * 0.5), size = 3) + 
      labs(
        title = "Demand, Wind Power, GT Dispatch, Bio Dispatch",
        x = "Time Index", y = "Power (MW)"
        )
}
```

# 1, Results from Default Data (without Subsidy)

## 1.1, Model 1 (without BEVs)

```{r, message=FALSE, fig.asp = 9/16, fig.width = 5}
ti_1 <- 
  get_result_dispatch("./results/without-subsidy/mat_x_result_1.csv", 1)

ti_1 %>% 
  plot_dispatch(2734.75, 0.0)
```

## 1.2, Model 2 (with BEVs)

```{r, message=FALSE, error=FALSE, fig.asp = 9/16, fig.width = 5}
ti_2 <- 
  get_result_dispatch_ev("./results/without-subsidy/mat_wind_u.csv",
    "./results/without-subsidy/mat_x_result_2.csv", 1)

ti_2 %>%
  plot_dispatch_ev(2565.3513, 0.0) 
```

# 2, Results from Modified Data (with Subsidy)

## 2.1, Model 1 (without BEVs)

```{r, message=FALSE, fig.asp = 9/16, fig.width = 5}
ti_3 <- 
  get_result_dispatch("./results/subsidy/mat_x_result_1.csv", 0.6249)

ti_3 %>% 
  plot_dispatch(1051.1959, 1802.1468)
```

Difference between total and net wind power output is the curtailed wind power.

## 2.2, Model 2 (with BEVs)

```{r, message=FALSE, fig.asp = 9/16, fig.width = 5}
ti_4 <- 
  get_result_dispatch_ev("./results/subsidy/mat_wind_u.csv",
    "./results/subsidy/mat_x_result_2.csv", 0.6242)

ti_4 %>%
  plot_dispatch_ev(707.9714, 1950.5787) 
```

`u` is the average charging or discharging speed.
 
# Sensitivity Analysis with Subsidized Data

```{r, message=FALSE}
ti_sense_c_fix_wind <- 
  read_csv(
    "./results/df_result_sensitivity_c_fix_wind.csv", 
    col_names = c("name", "value", "sensitivity", "whe_sub", "whe_ev")
    )
```

```{r, message=FALSE, fig.asp = 9/16, fig.width = 5}
ti_sense_c_fix_wind %>%
  filter(whe_ev == F) %>%
  # filter(name == "obj") %>%
  ggplot() + 
    geom_line(mapping = aes(x = sensitivity, y = value)) +
    facet_grid(rows = vars(name), scales = "free") +
    labs(x = "Fixed Cost of Wind (DKK / %)", y = "Value",
      title = "Sensitivity of Model without BEVs to Fixed Cost of Wind",
      subtitle = paste("Blue lines indicate the original fixed",
      "cost of wind, which is 2600000 DKK / %.")) +
    scale_x_continuous(sec.axis = dup_axis(name = "Variation Scale (%)", 
      ~ . / 52000000 * 20 * 100 - 100)) +
    geom_vline(xintercept = 52000000 / 20, color = "blue")
    
```

```{r, message=FALSE, fig.asp = 9/16, fig.width = 5}
ti_sense_c_fix_wind %>%
  filter(whe_ev == T) %>%
  ggplot() + 
    geom_line(mapping = aes(x = sensitivity, y = value)) +
    facet_grid(rows = vars(name), scales = "free") +
    labs(x = "Fixed Cost of Wind (DKK / %)", y = "Value",
      title = "Sensitivity of Model with BEVs to Fixed Cost of Wind",
      subtitle = paste("Blue lines indicate the original fixed",
      "cost of wind, which is 2600000 DKK / %.")) +
    scale_x_continuous(sec.axis = dup_axis(name = "Variation Scale (%)", 
      ~ . / 52000000 * 20 * 100 - 100)) +
    geom_vline(xintercept = 52000000 / 20, color = "blue")
```

```{r, message=FALSE}
ti_sense_c_var_gt <- 
  read_csv(
    "./results/df_result_sensitivity_c_var_gt.csv", 
    col_names = c("name", "value", "sensitivity", "whe_sub", "whe_ev")
    )
```

```{r, message=FALSE, fig.asp = 9/16, fig.width = 5}
ti_sense_c_var_gt %>%
  filter(whe_ev == F) %>%
  # filter(name == "obj") %>%
  ggplot() + 
    geom_line(mapping = aes(x = sensitivity, y = value)) +
    facet_grid(rows = vars(name), scales = "free") +
    labs(x = "Variable Cost of GT (DKK / MW)", y = "Value",
      title = "Sensitivity of Model without BEVs to Variable Cost of GT",
      subtitle = paste("Blue lines indicate the original variable cost of GT,",
      "which is 0.5 DKK / MW.")) +
    scale_x_continuous(sec.axis = dup_axis(name = "Variation Scale (%)", 
      ~ . / 0.5 * 100 - 100)) +
    geom_vline(xintercept = 0.5, color = "blue")
```

```{r, message=FALSE, fig.asp = 9/16, fig.width = 5}
ti_sense_c_var_gt %>%
  filter(whe_ev == T) %>%
  # filter(name == "obj") %>%
  ggplot() + 
    geom_line(mapping = aes(x = sensitivity, y = value)) +
    facet_grid(rows = vars(name), scales = "free") +
    labs(x = "Variable Cost of GT (DKK / MW)", y = "Value",
      title = "Sensitivity of Model with BEVs to Variable Cost of GT",
      subtitle = paste("Blue lines indicate the original variable cost of GT,",
      "which is 0.5 DKK / MW.")) +
    scale_x_continuous(sec.axis = dup_axis(name = "Variation Scale (%)", 
      ~ . / 0.5 * 100 - 100)) +
    geom_vline(xintercept = 0.5, color = "blue")
```

```{r, message=FALSE}
ti_sense_c_var_bio <- 
  read_csv(
    "./results/df_result_sensitivity_c_var_bio.csv", 
    col_names = c("name", "value", "sensitivity", "whe_sub", "whe_ev")
    )
```

```{r, message=FALSE, fig.asp = 9/16, fig.width = 5}
ti_sense_c_var_bio %>%
  filter(whe_ev == F) %>%
  # filter(name == "obj") %>%
  ggplot() + 
    geom_line(mapping = aes(x = sensitivity, y = value)) +
    facet_grid(rows = vars(name), scales = "free") +
    labs(x = "Variable Cost of Bio (DKK / MW)", y = "Value",
      title = "Sensitivity of Model without BEVs to Variable Cost of Bio",
      subtitle = paste("Blue lines indicate the original variable cost of Bio,",
      "which is 0.433 DKK / MW.")) +
    scale_x_continuous(sec.axis = dup_axis(name = "Variation Scale (%)", 
      ~ . / 0.433 * 100 - 100)) +
    geom_vline(xintercept = 0.433, color = "blue")
```

```{r, message=FALSE, fig.asp = 9/16, fig.width = 5}
ti_sense_c_var_bio %>%
  filter(whe_ev == T) %>%
  # filter(name == "obj") %>%
  ggplot() + 
    geom_line(mapping = aes(x = sensitivity, y = value)) +
    facet_grid(rows = vars(name), scales = "free") +
    labs(x = "Variable Cost of Bio (DKK / MW)", y = "Value",
      title = "Sensitivity of Model with BEVs to Variable Cost of Bio",
      subtitle = paste("Blue lines indicate the original variable cost of Bio,",
      "which is 0.433 DKK / MW.")) +
    scale_x_continuous(sec.axis = dup_axis(name = "Variation Scale (%)", 
      ~ . / 0.433 * 100 - 100)) +
    geom_vline(xintercept = 0.433, color = "blue")
```

```{r, message=FALSE}
ti_sense_scale_fleet <- 
  read_csv(
    "./results/df_result_sensitivity_scale_fleet.csv", 
    col_names = c("name", "value", "sensitivity", "whe_sub", "whe_ev")
    )
```

```{r, message=FALSE, fig.asp = 9/16, fig.width = 5}
ti_sense_scale_fleet %>%
  filter(whe_ev == T) %>%
  # filter(name == "obj") %>%
  ggplot() + 
    geom_line(mapping = aes(x = sensitivity, y = value)) +
    facet_grid(rows = vars(name), scales = "free") +
    labs(x = "Scale of BEVs Fleet", y = "Value",
      title = "Sensitivity of Model with BEVs to Scale of BEVs Fleet",
      subtitle = paste("Blue lines indicate the original scale of BEVs fleet,",
      "which is 1.")) +
    geom_vline(xintercept = 1, color = "blue")
```


